### ISSUE TITLE
in PHP

### ISSUE THREAD

**Issue by rfree** [mwgg/i3phtatus#1]
You appear to be using the PHP language in your application.

Why god, why.

**Comment by cryptiklemur** [comment]
@rfree [I can see why you think PHP is a bad language, from how you use it.](https://github.com/rfree/trivialpaste/blob/master/index.php)

**Comment by carpii** [comment]
boom! roasted.

**Comment by zeroedin-bill** [comment]
Holy crap. Looks like a bear ransacked php-scripts.com.

**Comment by Bilge** [comment]
# ![](http://vignette2.wikia.nocookie.net/someordinarygamers/images/7/73/90s-gifs-spinning-skull.gif/revision/latest?cb=20150315032848) #MEGAREKD ![](http://vignette2.wikia.nocookie.net/someordinarygamers/images/7/73/90s-gifs-spinning-skull.gif/revision/latest?cb=20150315032848)

**Comment by jwage** [comment]
LOL don't throw rocks when you live in a glass house.

**Comment by zeroedin-bill** [comment]
@jwage broadcast to tweeps immediately for lols
